<a href="https://colab.research.google.com/github/andycruz22/InteligenciaArtificial/blob/main/Andy_Cruz_de_NumPy_Exercises_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [1]:
# Import numpy as np and see the version

# your code here
import numpy as np
print(np.__version__)

1.25.2


In [2]:
# Create a 1D array of numbers from 0 to 9
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Create random vector of size 10 and replace the maximum value by 0
vector = np.random.rand(10)
print(vector)
print("\nValor max cambia a cero")
max = np.argmax(vector)
vector[max] = 0
print(vector)

[0.44917288 0.78731779 0.67278951 0.48227719 0.90045473 0.52709128
 0.75985674 0.3336025  0.48762142 0.6022339 ]

Valor max cambia a cero
[0.44917288 0.78731779 0.67278951 0.48227719 0.         0.52709128
 0.75985674 0.3336025  0.48762142 0.6022339 ]


In [4]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])

8


In [5]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [6]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:7])

[4 5 6 7]


In [7]:
# Create a 3×3 numpy array of all True’s
# your code here
array = np.full((3, 3), True, dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
# Extract all odd numbers from arr
# your code here
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7]


In [9]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
vect = np.arange(10, 50)
print(vect)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# Reverse a vector (first element becomes last)
vect = np.array([1, 2, 3, 4, 5])
vect_invertido = vect[::-1]
print(vect_invertido)

[5 4 3 2 1]


In [11]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
matriz = np.random.randint(0, 51, size=(10, 10))
valor_min = np.min(matriz)
valor_max = np.max(matriz)
print("Matriz:")
print(matriz)
print("\nValor min:", valor_min)
print("Valor max:", valor_max)

Matriz:
[[30 47  0 35 50 29 29 42 45 42]
 [ 8 31 28 49 41 38 38 21  2 22]
 [27 32 47 27 23 22 26 15 45 16]
 [32  0 20 46 44 38 44 50 23  9]
 [18 49 17 14 14 46 20  1 22  6]
 [41  1  1  7  0 45  0 21 29  5]
 [ 2 14 31 50 32  0  9 26  8 17]
 [39 36 14 35 37 14 29  3 12 13]
 [31  3 15  7 19 28  7 43  1  6]
 [37 11 39 34 48 10 47 20 30 20]]

Valor min: 0
Valor max: 50


In [12]:
# Create a 3x3x3 array with random values
array_3d = np.random.random((3, 3, 3))
print(array_3d)

[[[0.34530472 0.12094518 0.67300301]
  [0.17733627 0.87299706 0.30288412]
  [0.237366   0.12913382 0.4152293 ]]

 [[0.99753732 0.48755847 0.81302873]
  [0.49466746 0.77288314 0.39480059]
  [0.15307729 0.71930877 0.59569085]]

 [[0.18224049 0.06286929 0.32737393]
  [0.7906013  0.95462954 0.82735697]
  [0.33578285 0.57802318 0.96738651]]]


In [13]:
# Replace all odd numbers in arr with -1
arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1]


In [14]:
# Create an array of type float
arr_float = np.array([1.0, 2.5, 3.7, 4.2], dtype = float)
print(arr_float)
print(arr_float.dtype)

[1.  2.5 3.7 4.2]
float64


In [15]:
# Convert a 1D array to a 2D array with 2 rows
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape(2, -1)
print("Arr 1D:")
print(arr_1d)
print("\nArr 2D con 2 filas:")
print(arr_2d)

Arr 1D:
[1 2 3 4 5 6]

Arr 2D con 2 filas:
[[1 2 3]
 [4 5 6]]


In [16]:
# How to find common values between two arrays?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
valores_comunes = np.intersect1d(Z1, Z2)
print("Z1:", Z1)
print("Z2:", Z2)
print("Valores comunes:", valores_comunes)

Z1: [0 0 6 6 3 5 2 6 5 6]
Z2: [2 1 2 2 5 2 1 4 7 1]
Valores comunes: [2 5]


In [17]:
#  Consider two random array A and B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
comp = np.array_equal(A, B)
print("A:", A)
print("B:", B)
print("\n¿Son iguales?:", comp)



A: [1 0 1 1 1]
B: [0 1 0 0 0]

¿Son iguales?: False


In [18]:
# Stack arrays a and b vertically
vertical_A = np.vstack((A))
vertical_B = np.vstack((B))
apilado_v = np.array([[vertical_A],[vertical_B]])
print(apilado_v)

[[[[1]
   [0]
   [1]
   [1]
   [1]]]


 [[[0]
   [1]
   [0]
   [0]
   [0]]]]


In [19]:
# Stack the arrays a and b horizontally.
hori_A = np.hstack((A))
hori_B = np.hstack((B))
xd = np.array([[hori_A],[hori_B]])
print(xd)

[[[1 0 1 1 1]]

 [[0 1 0 0 0]]]


In [20]:
# Get all items between 5 and 10 from array tmp.
tmp = np.arange(15)
resultado = tmp[(tmp >= 5) & (tmp <= 10)]
print(tmp)
print("\nElementos entre 5 y 10:", resultado)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Elementos entre 5 y 10: [ 5  6  7  8  9 10]


In [21]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
# Vectorizar la función maxx
pair_max = np.vectorize(maxx)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
result = pair_max(a, b)
print("Arr a:", a)
print("Arr b:", b)
print("\nResultado:", result)


Arr a: [5 7 9 8 6 4 5]
Arr b: [6 3 4 8 9 7 1]

Resultado: [6 7 9 8 9 7 5]


In [22]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]
arr = np.arange(9).reshape(3,3)
print(arr)
# Intercambiar columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]
print("\nColumna 1 y 2 intercambiados:")
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]

Columna 1 y 2 intercambiados:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [23]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]
array_2d = np.random.uniform(5, 10, size=(5, 3))
print(array_2d)

[[7.76776994 7.57282702 5.50402395]
 [9.4204306  9.15639967 9.17327441]
 [5.3733287  7.83253276 7.88113829]
 [8.82069364 9.08135334 5.9634226 ]
 [6.02860002 8.85135546 9.7320673 ]]
