<a href="https://colab.research.google.com/github/andycruz22/InteligenciaArtificial/blob/main/Copia_de_Introducci%C3%B3n_a_Python_y_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# Import numpy as np and see the version

import numpy as np
print(np.__version__)

1.25.2


In [ ]:
# Create a 1D array of numbers from 0 to 9

array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Create random vector of size 10 and replace the maximum value by 0
vector = np.random.rand(10)
print(vector)

print("\nValor maximo cambiado a cero")
maximo = np.argmax(vector)
vector[maximo] = 0
print(vector)

[0.75302045 0.70753619 0.09594492 0.49939357 0.52018506 0.37523815
 0.23846818 0.06710877 0.9240106  0.96485005]

Valor maximo cambiado a cero
[0.75302045 0.70753619 0.09594492 0.49939357 0.52018506 0.37523815
 0.23846818 0.06710877 0.9240106  0.        ]


In [ ]:
# Print the number 8 from the array below:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])

8


In [ ]:
# Print the numbers [3, 4, 5] from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [ ]:
# Print the last 4 numbers from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-4:])

[4 5 6 7]


In [ ]:
# Create a 3×3 numpy array of all True’s
array = np.full((3, 3), True, dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Extract all odd numbers from arr
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7]


In [ ]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Reverse a vector (first element becomes last)
vector = np.array([1, 2, 3, 4, 5])
vector_invertido = vector[::-1]
print(vector_invertido)

[5 4 3 2 1]


In [ ]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
matriz = np.random.randint(0, 51, size=(10, 10))

valor_minimo = np.min(matriz)
valor_maximo = np.max(matriz)

print("Matriz:")
print(matriz)
print("\nValor mínimo:", valor_minimo)
print("Valor máximo:", valor_maximo)

Matriz:
[[24 15  3 41 47 44 10  8  6  7]
 [44  4 12 46 16 37 14 24  5 49]
 [ 1 27 44 37 36 36 36 50 37  0]
 [16 11 41  2 45 42 31 40 36  8]
 [10 36 49 40 45 10 16 16 30  4]
 [46 40 11 20 42 33 50 35 28 19]
 [18  5 28 14  6 11 22 15  9 24]
 [41 39 39 29 11  9 26 37 14 38]
 [45 37 50 23 29 40 17 14  5 14]
 [ 1 49 47 22 35  9 27 16 17 25]]

Valor mínimo: 0
Valor máximo: 50


In [ ]:
# Create a 3x3x3 array with random values
array_3d = np.random.random((3, 3, 3))
print(array_3d)

[[[0.46984697 0.11875307 0.34826   ]
  [0.77416623 0.61435375 0.35453776]
  [0.21736308 0.39621003 0.13001151]]

 [[0.23631128 0.5444229  0.46874797]
  [0.44549505 0.25984868 0.66487283]
  [0.34610716 0.63700223 0.73119441]]

 [[0.36482589 0.65177984 0.94108687]
  [0.1421145  0.05258151 0.84146925]
  [0.01909081 0.89450534 0.20071112]]]


In [ ]:
# Replace all odd numbers in arr with -1
arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1]


In [ ]:
# Create an array of type float
arr_float = np.array([1.5, 2.3, 3.1, 4.7, 5.5], dtype=float)

print(arr_float)
print(arr_float.dtype)

[1.5 2.3 3.1 4.7 5.5]
float64


In [ ]:
# Convert a 1D array to a 2D array with 2 rows
arr_1d = np.array([1, 2, 3, 4, 5, 6])

arr_2d = arr_1d.reshape(2, -1)

print("Array 1D:")
print(arr_1d)
print("\nArray 2D con 2 filas:")
print(arr_2d)

Array 1D:
[1 2 3 4 5 6]

Array 2D con 2 filas:
[[1 2 3]
 [4 5 6]]


In [ ]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

valores_comunes = np.intersect1d(Z1, Z2)

print("Z1:", Z1)
print("Z2:", Z2)
print("Valores comunes:", valores_comunes)

Z1: [7 1 0 1 8 8 6 6 6 0]
Z2: [8 3 1 5 2 5 4 6 3 9]
Valores comunes: [1 6 8]


In [ ]:
#  Consider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

comparacion = np.array_equal(A, B)

print("A:", A)
print("B:", B)
print("\n¿Son iguales?:", comparacion)

A: [1 0 0 0 1]
B: [1 1 1 0 0]

¿Son iguales?: False


In [ ]:
# Stack arrays a and b vertically
vertical_A = np.vstack((A))
vertical_B = np.vstack((B))

apilado_v = np.array([[vertical_A],[vertical_B]])
print(apilado_v)

[[[[1]
   [0]
   [0]
   [0]
   [1]]]


 [[[1]
   [1]
   [1]
   [0]
   [0]]]]


In [ ]:
# Stack the arrays a and b horizontally.
horizontal_A = np.hstack((A))
horizontal_B = np.hstack((B))

apilado_h = np.array([[horizontal_A],[horizontal_B]])
print(apilado_h)

[[[1 0 0 0 1]]

 [[1 1 1 0 0]]]


In [ ]:
# Get all items between 5 and 10 from array tmp.

tmp = np.arange(15)
resultado = tmp[(tmp >= 5) & (tmp <= 10)]

print(tmp)
print("\nElementos entre 5 y 10:", resultado)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Elementos entre 5 y 10: [ 5  6  7  8  9 10]


In [ ]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# Vectorizar la función maxx
pair_max = np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

resultado = pair_max(a, b)

print("Array a:", a)
print("Array b:", b)
print("\nResultado:", resultado)

Array a: [5 7 9 8 6 4 5]
Array b: [6 3 4 8 9 7 1]

Resultado: [6 7 9 8 9 7 5]


In [ ]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

arr = np.arange(9).reshape(3,3)
print(arr)

# Intercambiar columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("\nColumna 1 y 2 intercambiadas:")
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Columna 1 y 2 intercambiadas:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]


array_2d = np.random.uniform(5, 10, size=(5, 3))

print(array_2d)

[[7.02176982 8.53840558 5.72692721]
 [9.0716128  7.86119764 8.31972097]
 [7.07144604 5.72039858 8.00138348]
 [6.16505263 8.91508508 7.56715378]
 [6.44408856 6.76278673 6.14634262]]
